spring:
  application:
    name: "Gateway"
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: wigell-gym-service
              uri: http://wigell-gym-service-container:6565
              predicates:
                - Path=/api/wigellgym/**
              filters:
                - StripPrefix=1

            - id: wigell-travel-service
              uri: http://wigell-travel-service:8585
              predicates:
                - Path=/api/wigelltravels/v1/**
              filters:
                - StripPrefix=3

            - id: wigell-padel-service
              uri: http://wigell-padel:7575
              predicates:
                - Path=/api/wigellpadel/**
              filters:
                - StripPrefix=0

            - id: wigell-repair-service
              uri: http://wigell-repair:5555
              predicates:
                - Path=/api/wigellrepairs/**
              filters:
                - StripPrefix=0
server:
  port: 4545
